# Generated by Django 5.2.8 on 2025-11-18 15:52

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_front', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('aadhaar_back', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('address_proof', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('business_registration_proof', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('msme_certificate', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('partnership_deed', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('director_name', models.CharField(blank=True, max_length=120, null=True)),
                ('director_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('director_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('ubo_name', models.CharField(blank=True, max_length=120, null=True)),
                ('ubo_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('ubo_document', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('selfie', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('signature', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('board_resolution', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('bank_name_match', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=150)),
                ('business_type', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_proof', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
