# Generated by Django 5.2.8 on 2025-11-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_email_verified_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testkyc',
            name='email_verification_method',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='testkyc',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testkyc',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testkyc',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
