# Generated by Django 5.2.8 on 2025-11-20 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testkyc_email_verification_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=150, unique=True)),
                ('secret_key', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
