"""
Django settings for upi_project project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from pathlib import Path

# Optional: load .env file in development. Install python-dotenv: pip install python-dotenv
from dotenv import load_dotenv

# Project base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root if present
env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(env_path)

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable, fallback to an obviously insecure default (only dev)
SECRET_KEY = os.getenv('SECRET_KEY', 'replace-me-with-a-secret-in-production')

# DEBUG from env; default False for safety (set True only locally)
DEBUG = os.getenv('DEBUG', 'False').lower() in ('1', 'true', 'yes')

_raw_allowed = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,10.0.2.2,vetritechpay.onrender.com"
)

ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(",") if h.strip()]


AUTH_USER_MODEL = 'core.User'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # allauth apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
     'rest_framework',
    'core',
    'corsheaders',

]
SITE_ID = 1
INSTALLED_APPS += ["anymail"]   # make sure "INSTALLED_APPS" exists above
SOCIALACCOUNT_ADAPTER = "core.adapters.CustomSocialAdapter"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True

SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"


MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'core.middleware.IdempotencyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
     'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'upi_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5000",
    "http://localhost:5000",
   "https://vetritechpaytestsample.onrender.com",
   "http://10.0.2.2:8000",
]


WSGI_APPLICATION = 'upi_project.wsgi.application'

# Database (unchanged)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation (unchanged)
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Media
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' 
# Static files
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [ BASE_DIR / 'core' / 'static', ]
STATIC_URL = 'static/'

# Internationalization (unchanged)
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'   # ✅ Indian Standard Time
USE_I18N = True               # ✅ enables internationalization
USE_TZ = True 

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------- External service credentials (from env) ----------------
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')

RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')

# If you want, you can also ensure required secrets are present in production:
REQUIRE_SECRETS = os.getenv('REQUIRE_SECRETS', 'False').lower() in ('1','true','yes')
if REQUIRE_SECRETS and (not SECRET_KEY or SECRET_KEY == 'replace-me-with-a-secret-in-production'):
    raise RuntimeError('Missing SECRET_KEY in environment!')

# End of settings.py
import os




import os
ANYMAIL = {
    "SENDGRID_API_KEY": os.environ.get("SENDGRID_API_KEY"),
}
# --- Email (use env vars) ---
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
DEFAULT_NOTIFICATION_EMAIL='devakimathivarma@gmail.com'
EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_PORT = 587                   # TLS port
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "apikey"         # This is literally the username
EMAIL_HOST_PASSWORD = os.environ.get("SENDGRID_SMTP_PASSWORD")
DEFAULT_FROM_EMAIL = "mathivarmaganesan@gmail.com"

RAZORPAY_KEY_ID = "rzp_test_RP0oCMXlRICgfK"
RAZORPAY_KEY_SECRET = "9YwbHS9EcZnPl9Kkivo8Wa7L"
SENDGRID_API_KEY=os.environ.get("SENDGRID_API_KEY")


TIME_ZONE = 'Asia/Kolkata'
USE_TZ = False

RAZORPAY_KEY_ID = "rzp_test_RP0oCMXlRICgfK"
RAZORPAY_KEY_SECRET = "9YwbHS9EcZnPl9Kkivo8Wa7L"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # default
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
)


