# Generated by Django 5.2.8 on 2025-11-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_txn_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='i_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='upi_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
